spring:
  application:
    name: transaction_service
  threads:
    virtual:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: liquibase/changelog-master.yaml
    url: jdbc:postgresql://localhost:5432/transaction_service
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  datasource:
    hikari:
      connection-timeout: 10000
    url: jdbc:postgresql://localhost:5432/transaction_service
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  jackson:
    deserialization:
      fail-on-unknown-properties: false

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles:
        http.client.requests: 0.5, 0.75, 0.95, 0.99
        http.server.requests: 0.5, 0.75, 0.95, 0.99
      percentiles-histogram:
        http.client.requests: true
        http.server.requests: true

service:
  client:
    transaction:
      url: http://localhost:3008
      connect-timeout: 100ms
      read-timeout: 5s