spring:
  application:
    name: transaction_service
  threads:
    virtual:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: liquibase/changelog-master.yaml
    url: jdbc:postgresql://localhost:5432/transaction_service
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  datasource:
    hikari:
      connection-timeout: 10000
    url: jdbc:postgresql://localhost:5432/transaction_service
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  jackson:
    deserialization:
      fail-on-unknown-properties: false

service:
  client:
    transaction:
      url: http://localhost:9900
      connect-timeout: 100ms
      read-timeout: 1s