global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'virtual-threads'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: application
        replacement: virtual-threads